name: Generate code statistics

on: [push, pull_request]

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@v5
          with:
              concurrent_skipping: 'same_content_newer'
              skip_after_successful_duplicate: 'true'

  ts_bundle_stats:
    name: Bundle stats for TypeScript
    runs-on: ubuntu-latest

    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    steps:
      - uses: actions/checkout@v3
      - name: Cache Angular build assets
        uses: actions/cache@v3
        with:
          path: timApp/.angular/cache
          key: ${{ runner.os }}-angular-cache-stats-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-angular-cache-stats-
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            timApp/node_modules
          key: ${{ runner.os }}-ts-stats-npm-${{ hashFiles('timApp/package-lock.json') }}
      - name: Install packages
        run: |
          npm i --global npm@6
          cd timApp
          npm install
          npm install -g webpack-bundle-analyzer
      - name: Generate bundle statistics
        run: cd timApp && npm run statshtml
      - name: Upload stats
        uses: actions/upload-artifact@v4
        with:
          name: Bundle Report
          path: timApp/report.html